### ISSUE TITLE
Parameter Check

### ISSUE THREAD

**Issue by Geanik** [HazCod/maclaunch#1]
i just typed "macdown list disable <LaunchItem>" and it showed me a list
maybe you could implement some kind of parameter checking

**Comment by Geanik** [comment]
something like this
Line 117 - 128:
```
if [ $# -lt 1 ] || [ $# -gt 2 ]; then
    usage
fi

case "$1" in
    "list")
        if [ $# -eq 1 ]; then
            listItems
        else
            usage
        fi
    ;;
```

**Comment by HazCod** [comment]
Thank you @Geanik ! I commited it.
