### ISSUE TITLE
isSystemItemsDisabled: command not found

### ISSUE THREAD

**Issue by KishanBagaria** [hazcod/maclaunch#16]
https://github.com/hazcod/maclaunch/commit/facc78288c4c98c81e0bce88e7140b90ea9bd5d0 missed two instances of `isSystemItemsDisabled`

**Comment by hazcod** [comment]
Thank you for the fix!

**Comment by hazcod** [comment]
Fixed in release 2.3.1 + published on homebrew. 👍🏼
