### ISSUE TITLE
Missing startup plist at `/var/db/com.apple.xpc.launchd/`

### ISSUE THREAD

**Issue by ytgui** [hazcod/maclaunch#22]
+ Example of `/var/db/com.apple.xpc.launchd/loginitems.501.plist`:
```xml
<key>com.docker.helper</key>
<string>com.docker.docker</string>
<key>version.com.docker.helper</key>
<string>84025</string>
```

**Comment by hazcod** [comment]
Hi @ytgui , do you mean it misses the loginitems plist?
Are there multiple comparable plists? Would it be possible to share the contents (redacted) of those?

**Comment by hazcod** [comment]
Implementing in https://github.com/hazcod/maclaunch/pull/26
