### ISSUE TITLE
Doesn't work on Ventura.

### ISSUE THREAD

**Issue by user112200** [hazcod/maclaunch#24]
Is something happened? Last issue seems deleted.

`disable` does not work and launch status shows "OnStartup, MachService" instead of enabled or disabled.

**Comment by hazcod** [comment]
Hmmm that's odd. Can you share the plist file?

**Comment by user112200** [comment]
@hazcod 
![0](https://user-images.githubusercontent.com/84953364/201847114-4edf9c40-301e-42a6-a0f2-7b7637ed726b.png)
![1](https://user-images.githubusercontent.com/84953364/201847123-82d0967c-3706-4846-8843-f18a68c9c858.png)
![2](https://user-images.githubusercontent.com/84953364/201847125-e09b2ba3-30d4-4d7c-9731-4c1464b0462e.png)
File permissions on plist file:
![3](https://user-images.githubusercontent.com/84953364/201847126-12bc28a4-a13e-40a6-a8ed-5f60fb25b617.png)
Launchctl status:
![4](https://user-images.githubusercontent.com/84953364/201847130-e4434d31-c3be-4efa-ba42-c7e484dda96d.png)
Tried reinstalling with brew but same behavior. This bug only happens in Ventura. On Monterey it runs fine.

**Comment by hazcod** [comment]
@user112200 Can you try providing me the contents of the plist which doesn't work so I can reproduce?
(One of the Adobe ones in this case)

**Comment by user112200** [comment]
@hazcod
Content of com.adobe.AdobeCreativeCloud.plist
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.adobe.AdobeCreativeCloud</string>
	<key>Program</key>
	<string>/Applications/Utilities/Adobe Creative Cloud/ACC/Creative Cloud.app/Contents/MacOS/Creative Cloud</string>
	<key>ProgramArguments</key>
	<array>
		<string>/Applications/Utilities/Adobe Creative Cloud/ACC/Creative Cloud.app/Contents/MacOS/Creative Cloud</string>
		<string>--showwindow=false</string>
		<string>--onOSstartup=true</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>
```

**Comment by hazcod** [comment]
@user112200 Thank you! I've finally found the breaking change and issued a fix in .
Can you try the maclaunch version [here](https://raw.githubusercontent.com/hazcod/maclaunch/fix/ventura/maclaunch.sh)?
You can download it locally, `chmod 700` it and `./maclaunch list adobe`. Thanks!

**Comment by user112200** [comment]
@hazcod That's great! Here's my result:
![ss1](https://user-images.githubusercontent.com/84953364/201854356-1d58ce49-07b3-48d4-bf9f-0a01c53d9553.png)
without sudo
![ss2](https://user-images.githubusercontent.com/84953364/201854384-c2a8f295-dcc9-4722-ad55-1669166415e8.png)

**Comment by hazcod** [comment]
Great! I'll issue a new release today, just want to fix loginItems in Ventura too.
What are the contents of that `custom.plist`?

**Comment by user112200** [comment]
That's great to hear!
Custom.plist is just personal development test program starter. I just used boilterplate so it doesn't have any label or name. Looks something like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" “http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
     <key>Label</key>
     <string>custom script</string>

     <key>RunAtLoad</key>
     <true/>

     <key>KeepAlive</key>
     <true/>

     <key>Program</key>
     <string>/Applications/something/something</string>

     <key>ProgramArguments</key>
     <array>
      <string>-o Arguments</string>
     </array>
  </dict>
</plist>
```

**Comment by user112200** [comment]
Super!
