### ISSUE TITLE
Cant revert disable an item

### ISSUE THREAD

**Issue by Zorak924** [hazcod/maclaunch#29]
![Capture d’écran 41](https://github.com/hazcod/maclaunch/assets/78243244/0f7f908c-6378-4790-8672-ba36a48e144e)

I've disabled the item for a certain amount of time but it wont revert when i set the scrpt to maclaunch enable ... even with sudo

**Comment by hazcod** [comment]
Hi @Zorak924 , can you run `set -ex` and run the command again and see if it echoes the `launchctl enable` command and its error?

**Comment by Zorak924** [comment]
All my services are reseted with `set -ex` but if i redo the same command it's still not working even `launchctl`

**Comment by hazcod** [comment]
What does this return?
```shell
launchctl disable user/"$(id -u)"/com.avid.bsd.shoetoolv120
```
