### ISSUE TITLE
Detect duplicates

### ISSUE THREAD

**Issue by hrvstr** [hazcod/maclaunch#6]
Some apps will reinstall all their launch daemons with every update. Would it be possible to add a check if an identical enabled and disabled version was found? E.g.

foo.bar.plist
foo.bar.plist.disabled
[DUPLICATE] Do you want to disable "foo.bar.plist" again? y/n

**Comment by hazcod** [comment]
@hrvstr Can you elaborate on the problem here?
In a way it's natural that maclaunch will mention it twice since there really are two plists on the filesystem.
Can you paste a snippet of the maclaunch output with those plists?

**Comment by hazcod** [comment]
This will be fixed with https://github.com/hazcod/maclaunch/issues/6
Closing, please reopen if it still reoccurs.
